### ISSUE TITLE
Feature Request: Exporting Data

### ISSUE THREAD

**Issue by honggoff** [Sensirion/SmartGadget-Android#28]
From what I can tell, there is no easy way to get the data out of the application in the moment. I want a save / share button that lets you export data in a human readable text format.

**Comment by Henning-Lenz** [comment]
I second that! The SmartGadget could be such a nice out-of-the-box datalogger if the data could be exported in some format. Only viewing data in the app is limiting possibilities drastically for most purposes.

**Comment by mghijs** [comment]
Hi, would there be an update on this so far please?
We need to analyse the logged humidity data offline, would there be any way to do this now?

**Comment by abrauchli** [comment]
Hi Everyone, there's been some development on this issue and I'm happy to say that our new app MyAmbience (link below) features data export. I know many have been waiting for this. On the sad side, the source code for MyAmbience will, at least for the foreseeable future, not be released publicly and further development on SmartGadget-Android is not to be expected - although pull requests will *likely*, time permitting, be reviewed and considered. I'll leave the issue opened since it's not fixed in SmartGadget-Android.

https://play.google.com/store/apps/details?id=com.sensirion.myambience

Kind regards from the Sensirion Team
