### ISSUE TITLE
paired, but not discovered 

### ISSUE THREAD

**Issue by Cathryne** [Sensirion/SmartGadget-Android#36]
Hello!

I have two [SHT31s](https://www.sensirion.com/products/humidity-sensors/development-kit/), and [the app v1.8.1](https://f-droid.org/repository/browse/?fdid=com.sensirion.smartgadget) on a [S4mini with CyanogenMod](https://wiki.cyanogenmod.org/w/Serranoltexx_Info) 13. The phone pairs with the SHT31s, but the app doesn't discover them under `Settings > Connections > Smart Gadgets` (screenshot from the app switcher at the bottom).

Whenever the app asks for Bluetooth permissions, I click allow. I tried in Flight mode and with all other apps closed. [BLExplorer](https://f-droid.org/repository/browse/?fdid=org.ligi.blexplorer) I sees "Smart Humigadget" & also connects. However, the Smart Gadget app scans without ever discovering the SHT31 :-(

What could be wrong here? What info can I provide to help the trouble-shooting? Thanks for any help with this issue :-)

![img_20161126_111320](https://cloud.githubusercontent.com/assets/757323/20639874/fc3f3528-b3cf-11e6-9ac0-5e5a76fd18a1.jpg)
![screenshot_20161126-115851](https://cloud.githubusercontent.com/assets/757323/20639916/9b39a000-b3d0-11e6-85e1-56ac85ec9e48.png)
![screenshot_20161126-111245](https://cloud.githubusercontent.com/assets/757323/20639850/f893868c-b3ce-11e6-9273-a82d9a59032e.png)

**Comment by abrauchli** [comment]
Hi Cathryne,

Thanks for posting here. Can you make sure that location is enabled in your settings > Location. It doesn't matter if it's set to "High precision", "battery saving" or "device only", but for some reason, the scan turns out empty otherwise. Also, you have to allow access to your location when asked - the message is misleading because the Smart Gadget app is not interested in your location (see source code) but in the device's hardware address.

A bit of background: When you get a device hardware addresses you could technically map those and/or look them up in a database to get a location, which is what the coarse location feature does.

Let me know if that helped.
