### ISSUE TITLE
App doesn't identify the SHT31 sensor

### ISSUE THREAD

**Issue by JackFlash3** [Sensirion/SmartGadget-Android#43]
Hello Sensirion,

I'm running the smart gadget on an Android version 5.0.2, locations and Bluetooth services enabled.
Yet I can't connect to my sensor. Bluetooth and Locations in my phone seems to be working well with other instruments and /or apps.

The sensor itself seems to be fine cause I'm logging to it from other phones. 

Can you tell me what might be the problem? Is the Android version too old? In the google playit says that it should be working with Lolipop and up.

Thnaks,
Eyal

**Comment by abrauchli** [comment]
Dear Eyal,

The software stack of Android 5 should work, however some phones with earlier Bluetooth chips are known to have issues with BLE (Bluetooth Low Energy), which the Smart Gadget uses.

Just make sure you did not pair the device from the Settings dialog as this seems to cause issues. Also make sure that no other mobile device is connected to the Smart Gadget. The Bluetooth icon on the gadget's LCD should be flashing, if it's permanently lit another device is already connected, preventing a further connection.

Closing the issue since it's likely related to your phone's hardware.

Kind regards
