### ISSUE TITLE
adding "Download" button on History panel.  

### ISSUE THREAD

**Issue by saule** [Sensirion/SmartGadget-Android#46]
Hello, 
I have added button on History panel. 
when button is pressed, Excel file will be generated, with all the history data.
I am new in open source, could I contribute my code to close this issue?

**Comment by abrauchli** [comment]
Hi @saule Thanks for your interest in SmartGadget. Let me say that any contributions are greatly appreciated, however that does not mean that they will automatically be mainlined (merged back into the app). But you should definitely push your code online such that other people can benefit from it, then you can open a pull request to start the review process. Start by forking the project and pushing your commits to a new branch. The create a pull request on that branch.

We are very open to the idea of having data export, but I have my doubts that Excel is the format. Having said that, csv is likely not too far off your solution, and Excel should be able to open it too. We're open to hearing other suggestions too...

Note that after the original pull request, your code will likely have to be reworked a few times in order to meet the review criteria. Do not be discouraged, it serves to improve the overall quality and should not be taken personally.

I'll be closing this issue since it's a duplicate of #28.

**Comment by saule** [comment]
@abrauchli thank you very much for your response. I will try to do  as a CSV file.
Any review will be very helpful to me.
